/*
 * tiles.h - sprite atlases (generated by tools/gen_tiles.py from the original game's graphics).
 * Each atlas is one column of square tiles in the framebuffer pixel order; 0xF81F = transparent.
 * SPDX-License-Identifier: MIT
 */
#pragma once

#include <stdint.h>

enum TileId {
    T_FLOOR = 0, T_WALL, T_GOAL, T_BOX, T_BOX_GOAL,
    T_PLAYER = 5,          // 16 frames: left 0-3, right 4-7, up 8-11, down 12-15
    T_COUNT = 21
};

constexpr uint16_t TILE_KEY = 0xF81F;

extern const uint16_t TILES_24[T_COUNT * 24 * 24];
extern const uint16_t TILES_16[T_COUNT * 16 * 16];
extern const uint16_t TILES_12[T_COUNT * 12 * 12];
