// GENERATED by tools/gen_i18n.py - edit the table there, not this file.
// UTF-8, lowercase accents only (the 8x8 font has no uppercase accented glyph).
#include "i18n.h"

namespace i18n {

static int s_lang = FR;

static const char* const T[LANG_COUNT][S_COUNT] = {
  {  // FR
    "Jouer",  // S_PLAY
    "Options",  // S_OPTIONS
    "Crédits",  // S_CREDITS
    "Quitter",  // S_QUIT
    "Choisis un pack",  // S_CHOOSE_PACK
    "Choisis un niveau",  // S_CHOOSE_LEVEL
    "%d niveaux",  // S_LEVELS_FMT
    "Niveau %d",  // S_LEVEL_FMT
    "Coups",  // S_MOVES
    "Poussées",  // S_PUSHES
    "Verrouillé",  // S_LOCKED
    "Niveau terminé !",  // S_SOLVED
    "A : niveau suivant",  // S_SOLVED_NEXT
    "Pack terminé, bravo !",  // S_PACK_DONE
    "Pause",  // S_PAUSE
    "Reprendre",  // S_RESUME
    "Recommencer",  // S_RESTART
    "Choix du niveau",  // S_LEVEL_SELECT
    "Ecran titre",  // S_TO_TITLE
    "Langue",  // S_OPT_LANGUAGE
    "Musique",  // S_OPT_MUSIC
    "Bruitages",  // S_OPT_SFX
    "Mouvement fluide",  // S_OPT_ANIM
    "Tous les niveaux",  // S_OPT_UNLOCK
    "oui",  // S_ON
    "non",  // S_OFF
    "Retour",  // S_BACK
    "Aucun pack de niveaux",  // S_NO_PACKS
    "Pack illisible",  // S_LOAD_ERROR
    "Capture enregistrée",  // S_SHOT_SAVED
    "Capture impossible",  // S_SHOT_FAILED
    "(niveaux d'initiation)",  // S_BUILTIN_HINT
    "B:annuler A:refaire C:recommencer",  // S_HELP_GAME
    "A:valider B:retour",  // S_HELP_MENU
    "A:jouer B:retour L/R:+-5",  // S_HELP_LEVELS
    "Quitter le jeu ?",  // S_QUIT_CONFIRM
    "Oui",  // S_YES
    "Non",  // S_NO
    "Jeu d'origine",  // S_CR_TITLE_GAME
    "Graphismes",  // S_CR_TITLE_ART
    "Musique et sons",  // S_CR_TITLE_SOUND
    "Niveaux",  // S_CR_TITLE_LEVELS
    "Portage AKA",  // S_CR_TITLE_PORT
    "%d/%d",  // S_PAGE_FMT
    "Editeur de niveaux",  // S_EDITOR
    "Mes packs (éditeur)",  // S_ED_PACKS_TITLE
    "Nouveau pack",  // S_ED_NEW_PACK
    "Nouveau niveau",  // S_ED_NEW_LEVEL
    "Tester le niveau",  // S_ED_TEST
    "Enregistrer et quitter",  // S_ED_SAVE
    "Quitter sans enregistrer",  // S_ED_DISCARD
    "Tout effacer",  // S_ED_CLEAR
    "Pack enregistré",  // S_ED_SAVED
    "Ecriture impossible",  // S_ED_SAVE_FAILED
    "D encore : supprimer",  // S_ED_DELETE_CONFIRM
    "Test réussi !",  // S_ED_TEST_OK
    "Effacer",  // S_ED_ERASE
    "Mur",  // S_ED_WALL
    "Cible",  // S_ED_GOAL
    "Caisse",  // S_ED_BOX
    "Joueur",  // S_ED_PLAYER
    "A:pose C:efface L/R:pièce B:menu D:test",  // S_ED_HELP
    "A:éditer D x2:supprimer B:retour",  // S_ED_LIST_HELP
    "Pack trop gros pour l'éditeur",  // S_ED_PACK_TOO_BIG
    "Il faut des murs",  // S_ST_EMPTY
    "Niveau trop grand",  // S_ST_TOOBIG
    "Il manque le joueur",  // S_ST_NOPLAYER
    "Un seul joueur !",  // S_ST_MANYPLAYERS
    "Il manque des caisses",  // S_ST_NOBOX
    "Il manque des cibles",  // S_ST_NOGOAL
    "Plus de cibles que de caisses",  // S_ST_MISMATCH
  },
  {  // EN
    "Play",  // S_PLAY
    "Options",  // S_OPTIONS
    "Credits",  // S_CREDITS
    "Quit",  // S_QUIT
    "Choose a pack",  // S_CHOOSE_PACK
    "Choose a level",  // S_CHOOSE_LEVEL
    "%d levels",  // S_LEVELS_FMT
    "Level %d",  // S_LEVEL_FMT
    "Moves",  // S_MOVES
    "Pushes",  // S_PUSHES
    "Locked",  // S_LOCKED
    "Level complete!",  // S_SOLVED
    "A: next level",  // S_SOLVED_NEXT
    "Pack finished, well done!",  // S_PACK_DONE
    "Paused",  // S_PAUSE
    "Resume",  // S_RESUME
    "Restart",  // S_RESTART
    "Level select",  // S_LEVEL_SELECT
    "Title screen",  // S_TO_TITLE
    "Language",  // S_OPT_LANGUAGE
    "Music",  // S_OPT_MUSIC
    "Sound fx",  // S_OPT_SFX
    "Smooth moves",  // S_OPT_ANIM
    "All levels open",  // S_OPT_UNLOCK
    "on",  // S_ON
    "off",  // S_OFF
    "Back",  // S_BACK
    "No level pack found",  // S_NO_PACKS
    "Pack unreadable",  // S_LOAD_ERROR
    "Screenshot saved",  // S_SHOT_SAVED
    "Screenshot failed",  // S_SHOT_FAILED
    "(starter levels)",  // S_BUILTIN_HINT
    "B:undo A:redo C:restart",  // S_HELP_GAME
    "A:select B:back",  // S_HELP_MENU
    "A:play B:back L/R:+-5",  // S_HELP_LEVELS
    "Quit the game?",  // S_QUIT_CONFIRM
    "Yes",  // S_YES
    "No",  // S_NO
    "Original game",  // S_CR_TITLE_GAME
    "Graphics",  // S_CR_TITLE_ART
    "Music and sound",  // S_CR_TITLE_SOUND
    "Levels",  // S_CR_TITLE_LEVELS
    "AKA port",  // S_CR_TITLE_PORT
    "%d/%d",  // S_PAGE_FMT
    "Level editor",  // S_EDITOR
    "My packs (editor)",  // S_ED_PACKS_TITLE
    "New pack",  // S_ED_NEW_PACK
    "New level",  // S_ED_NEW_LEVEL
    "Test the level",  // S_ED_TEST
    "Save and exit",  // S_ED_SAVE
    "Exit without saving",  // S_ED_DISCARD
    "Clear all",  // S_ED_CLEAR
    "Pack saved",  // S_ED_SAVED
    "Cannot write the file",  // S_ED_SAVE_FAILED
    "Press D again to delete",  // S_ED_DELETE_CONFIRM
    "Test passed!",  // S_ED_TEST_OK
    "Erase",  // S_ED_ERASE
    "Wall",  // S_ED_WALL
    "Goal",  // S_ED_GOAL
    "Box",  // S_ED_BOX
    "Player",  // S_ED_PLAYER
    "A:put C:erase L/R:part B:menu D:test",  // S_ED_HELP
    "A:edit D x2:delete B:back",  // S_ED_LIST_HELP
    "Pack too big for the editor",  // S_ED_PACK_TOO_BIG
    "Walls are missing",  // S_ST_EMPTY
    "Level too big",  // S_ST_TOOBIG
    "The player is missing",  // S_ST_NOPLAYER
    "Only one player!",  // S_ST_MANYPLAYERS
    "Boxes are missing",  // S_ST_NOBOX
    "Goals are missing",  // S_ST_NOGOAL
    "More goals than boxes",  // S_ST_MISMATCH
  },
  {  // DE
    "Spielen",  // S_PLAY
    "Optionen",  // S_OPTIONS
    "Mitwirkende",  // S_CREDITS
    "Beenden",  // S_QUIT
    "Wähle ein Paket",  // S_CHOOSE_PACK
    "Wähle ein Level",  // S_CHOOSE_LEVEL
    "%d Level",  // S_LEVELS_FMT
    "Level %d",  // S_LEVEL_FMT
    "Züge",  // S_MOVES
    "Schübe",  // S_PUSHES
    "Gesperrt",  // S_LOCKED
    "Level geschafft!",  // S_SOLVED
    "A: nächstes Level",  // S_SOLVED_NEXT
    "Paket gelöst, bravo!",  // S_PACK_DONE
    "Pause",  // S_PAUSE
    "Weiter",  // S_RESUME
    "Neustart",  // S_RESTART
    "Levelauswahl",  // S_LEVEL_SELECT
    "Titelbild",  // S_TO_TITLE
    "Sprache",  // S_OPT_LANGUAGE
    "Musik",  // S_OPT_MUSIC
    "Effekte",  // S_OPT_SFX
    "Weiche Bewegung",  // S_OPT_ANIM
    "Alle Level offen",  // S_OPT_UNLOCK
    "an",  // S_ON
    "aus",  // S_OFF
    "Zurück",  // S_BACK
    "Keine Levelpakete",  // S_NO_PACKS
    "Paket unlesbar",  // S_LOAD_ERROR
    "Bildschirmfoto gespeichert",  // S_SHOT_SAVED
    "Bildschirmfoto fehlgeschlagen",  // S_SHOT_FAILED
    "(Einsteiger-Level)",  // S_BUILTIN_HINT
    "B:zurück A:vor C:neu",  // S_HELP_GAME
    "A:wählen B:zurück",  // S_HELP_MENU
    "A:los B:zurück L/R:+-5",  // S_HELP_LEVELS
    "Spiel beenden?",  // S_QUIT_CONFIRM
    "Ja",  // S_YES
    "Nein",  // S_NO
    "Originalspiel",  // S_CR_TITLE_GAME
    "Grafik",  // S_CR_TITLE_ART
    "Musik und Klang",  // S_CR_TITLE_SOUND
    "Level",  // S_CR_TITLE_LEVELS
    "AKA-Portierung",  // S_CR_TITLE_PORT
    "%d/%d",  // S_PAGE_FMT
    "Leveleditor",  // S_EDITOR
    "Meine Pakete (Editor)",  // S_ED_PACKS_TITLE
    "Neues Paket",  // S_ED_NEW_PACK
    "Neues Level",  // S_ED_NEW_LEVEL
    "Level testen",  // S_ED_TEST
    "Speichern und beenden",  // S_ED_SAVE
    "Ohne Speichern beenden",  // S_ED_DISCARD
    "Alles löschen",  // S_ED_CLEAR
    "Paket gespeichert",  // S_ED_SAVED
    "Schreiben fehlgeschlagen",  // S_ED_SAVE_FAILED
    "D nochmal: löschen",  // S_ED_DELETE_CONFIRM
    "Test bestanden!",  // S_ED_TEST_OK
    "Radieren",  // S_ED_ERASE
    "Wand",  // S_ED_WALL
    "Ziel",  // S_ED_GOAL
    "Kiste",  // S_ED_BOX
    "Spieler",  // S_ED_PLAYER
    "A:setzen C:weg L/R:Teil B:Menü D:Test",  // S_ED_HELP
    "A:ändern D x2:löschen B:zurück",  // S_ED_LIST_HELP
    "Paket zu groß für den Editor",  // S_ED_PACK_TOO_BIG
    "Wände fehlen",  // S_ST_EMPTY
    "Level zu groß",  // S_ST_TOOBIG
    "Spieler fehlt",  // S_ST_NOPLAYER
    "Nur ein Spieler!",  // S_ST_MANYPLAYERS
    "Kisten fehlen",  // S_ST_NOBOX
    "Ziele fehlen",  // S_ST_NOGOAL
    "Mehr Ziele als Kisten",  // S_ST_MISMATCH
  },
  {  // ES
    "Jugar",  // S_PLAY
    "Opciones",  // S_OPTIONS
    "Créditos",  // S_CREDITS
    "Salir",  // S_QUIT
    "Elige un pack",  // S_CHOOSE_PACK
    "Elige un nivel",  // S_CHOOSE_LEVEL
    "%d niveles",  // S_LEVELS_FMT
    "Nivel %d",  // S_LEVEL_FMT
    "Pasos",  // S_MOVES
    "Empujes",  // S_PUSHES
    "Bloqueado",  // S_LOCKED
    "¡Nivel completado!",  // S_SOLVED
    "A: nivel siguiente",  // S_SOLVED_NEXT
    "¡Pack terminado, bravo!",  // S_PACK_DONE
    "Pausa",  // S_PAUSE
    "Continuar",  // S_RESUME
    "Reiniciar",  // S_RESTART
    "Elegir nivel",  // S_LEVEL_SELECT
    "Pantalla de título",  // S_TO_TITLE
    "Idioma",  // S_OPT_LANGUAGE
    "Música",  // S_OPT_MUSIC
    "Efectos",  // S_OPT_SFX
    "Movimiento suave",  // S_OPT_ANIM
    "Todos los niveles",  // S_OPT_UNLOCK
    "sí",  // S_ON
    "no",  // S_OFF
    "Volver",  // S_BACK
    "Ningún pack de niveles",  // S_NO_PACKS
    "Pack ilegible",  // S_LOAD_ERROR
    "Captura guardada",  // S_SHOT_SAVED
    "Captura imposible",  // S_SHOT_FAILED
    "(niveles de iniciación)",  // S_BUILTIN_HINT
    "B:deshacer A:rehacer C:reiniciar",  // S_HELP_GAME
    "A:aceptar B:volver",  // S_HELP_MENU
    "A:jugar B:volver L/R:+-5",  // S_HELP_LEVELS
    "¿Salir del juego?",  // S_QUIT_CONFIRM
    "Sí",  // S_YES
    "No",  // S_NO
    "Juego original",  // S_CR_TITLE_GAME
    "Gráficos",  // S_CR_TITLE_ART
    "Música y sonido",  // S_CR_TITLE_SOUND
    "Niveles",  // S_CR_TITLE_LEVELS
    "Versión AKA",  // S_CR_TITLE_PORT
    "%d/%d",  // S_PAGE_FMT
    "Editor de niveles",  // S_EDITOR
    "Mis packs (editor)",  // S_ED_PACKS_TITLE
    "Nuevo pack",  // S_ED_NEW_PACK
    "Nuevo nivel",  // S_ED_NEW_LEVEL
    "Probar el nivel",  // S_ED_TEST
    "Guardar y salir",  // S_ED_SAVE
    "Salir sin guardar",  // S_ED_DISCARD
    "Borrar todo",  // S_ED_CLEAR
    "Pack guardado",  // S_ED_SAVED
    "No se pudo escribir",  // S_ED_SAVE_FAILED
    "D otra vez: borrar",  // S_ED_DELETE_CONFIRM
    "¡Prueba superada!",  // S_ED_TEST_OK
    "Borrar",  // S_ED_ERASE
    "Muro",  // S_ED_WALL
    "Meta",  // S_ED_GOAL
    "Caja",  // S_ED_BOX
    "Jugador",  // S_ED_PLAYER
    "A:poner C:borra L/R:pieza B:menú D:test",  // S_ED_HELP
    "A:editar D x2:borrar B:volver",  // S_ED_LIST_HELP
    "Pack demasiado grande",  // S_ED_PACK_TOO_BIG
    "Faltan muros",  // S_ST_EMPTY
    "Nivel demasiado grande",  // S_ST_TOOBIG
    "Falta el jugador",  // S_ST_NOPLAYER
    "¡Un solo jugador!",  // S_ST_MANYPLAYERS
    "Faltan cajas",  // S_ST_NOBOX
    "Faltan metas",  // S_ST_NOGOAL
    "Más metas que cajas",  // S_ST_MISMATCH
  },
  {  // IT
    "Gioca",  // S_PLAY
    "Opzioni",  // S_OPTIONS
    "Crediti",  // S_CREDITS
    "Esci",  // S_QUIT
    "Scegli un pacchetto",  // S_CHOOSE_PACK
    "Scegli un livello",  // S_CHOOSE_LEVEL
    "%d livelli",  // S_LEVELS_FMT
    "Livello %d",  // S_LEVEL_FMT
    "Mosse",  // S_MOVES
    "Spinte",  // S_PUSHES
    "Bloccato",  // S_LOCKED
    "Livello completato!",  // S_SOLVED
    "A: livello successivo",  // S_SOLVED_NEXT
    "Pacchetto finito, bravo!",  // S_PACK_DONE
    "Pausa",  // S_PAUSE
    "Riprendi",  // S_RESUME
    "Ricomincia",  // S_RESTART
    "Scelta livello",  // S_LEVEL_SELECT
    "Schermata titolo",  // S_TO_TITLE
    "Lingua",  // S_OPT_LANGUAGE
    "Musica",  // S_OPT_MUSIC
    "Effetti",  // S_OPT_SFX
    "Movimento fluido",  // S_OPT_ANIM
    "Tutti i livelli",  // S_OPT_UNLOCK
    "sì",  // S_ON
    "no",  // S_OFF
    "Indietro",  // S_BACK
    "Nessun pacchetto",  // S_NO_PACKS
    "Pacchetto illeggibile",  // S_LOAD_ERROR
    "Schermata salvata",  // S_SHOT_SAVED
    "Schermata non riuscita",  // S_SHOT_FAILED
    "(livelli iniziali)",  // S_BUILTIN_HINT
    "B:annulla A:ripeti C:ricomincia",  // S_HELP_GAME
    "A:ok B:indietro",  // S_HELP_MENU
    "A:gioca B:indietro L/R:+-5",  // S_HELP_LEVELS
    "Uscire dal gioco?",  // S_QUIT_CONFIRM
    "Sì",  // S_YES
    "No",  // S_NO
    "Gioco originale",  // S_CR_TITLE_GAME
    "Grafica",  // S_CR_TITLE_ART
    "Musica e suoni",  // S_CR_TITLE_SOUND
    "Livelli",  // S_CR_TITLE_LEVELS
    "Porting AKA",  // S_CR_TITLE_PORT
    "%d/%d",  // S_PAGE_FMT
    "Editor di livelli",  // S_EDITOR
    "I miei pacchetti (editor)",  // S_ED_PACKS_TITLE
    "Nuovo pacchetto",  // S_ED_NEW_PACK
    "Nuovo livello",  // S_ED_NEW_LEVEL
    "Prova il livello",  // S_ED_TEST
    "Salva ed esci",  // S_ED_SAVE
    "Esci senza salvare",  // S_ED_DISCARD
    "Cancella tutto",  // S_ED_CLEAR
    "Pacchetto salvato",  // S_ED_SAVED
    "Scrittura impossibile",  // S_ED_SAVE_FAILED
    "D ancora: elimina",  // S_ED_DELETE_CONFIRM
    "Test superato!",  // S_ED_TEST_OK
    "Cancella",  // S_ED_ERASE
    "Muro",  // S_ED_WALL
    "Obiettivo",  // S_ED_GOAL
    "Cassa",  // S_ED_BOX
    "Giocatore",  // S_ED_PLAYER
    "A:metti C:canc L/R:pezzo B:menu D:test",  // S_ED_HELP
    "A:modifica D x2:elimina B:indietro",  // S_ED_LIST_HELP
    "Pacchetto troppo grande",  // S_ED_PACK_TOO_BIG
    "Mancano i muri",  // S_ST_EMPTY
    "Livello troppo grande",  // S_ST_TOOBIG
    "Manca il giocatore",  // S_ST_NOPLAYER
    "Un solo giocatore!",  // S_ST_MANYPLAYERS
    "Mancano le casse",  // S_ST_NOBOX
    "Mancano gli obiettivi",  // S_ST_NOGOAL
    "Più obiettivi che casse",  // S_ST_MISMATCH
  },
};

static const char* const NAMES[LANG_COUNT] = { "Français", "English", "Deutsch", "Español", "Italiano" };

void set_lang(int l) { s_lang = (l >= 0 && l < LANG_COUNT) ? l : FR; }
int lang() { return s_lang; }
const char* lang_name(int l) { return (l >= 0 && l < LANG_COUNT) ? NAMES[l] : NAMES[EN]; }
const char* tr(Str s) { return (s >= 0 && s < S_COUNT) ? T[s_lang][s] : ""; }

}  // namespace i18n
