#!/usr/bin/env python3
"""Generates main/assets/tiles_data.cpp from the original sprites (assets/original/graphics).

The sprites come from Sokoban (GP2X) by Willems Davy (MIT); wall: 1001.com (CC-BY-SA 3.0),
floor and player: Kenney (CC0), box: SpriteAttack (CC0). See CREDITS.md.

Three sizes are produced (24, 16, 12 px) so that a 26x15 level fits the 320x240 screen.
Atlas = one column of tiles; pixels are in the native framebuffer order (R | G<<5 | B<<11),
0xF81F means transparent.
"""
import os, sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets", "original", "graphics")
OUT = os.path.join(ROOT, "main", "assets", "tiles_data.cpp")
KEY = 0xF81F
SIZES = (24, 16, 12)

# tile order (must match tiles.h)
NAMES = ["floor", "wall", "goal", "box", "box_on_goal"] + ["player%d" % i for i in range(16)]


def load_tiles():
    floor = Image.open(os.path.join(SRC, "floor.png")).convert("RGBA")
    wall = Image.open(os.path.join(SRC, "wall.png")).convert("RGBA")
    spot = Image.open(os.path.join(SRC, "spot.png")).convert("RGBA")
    box = Image.open(os.path.join(SRC, "box.png")).convert("RGBA")
    pl = Image.open(os.path.join(SRC, "player.png")).convert("RGBA")
    t = [floor, wall, spot, box.crop((0, 0, 24, 24)), box.crop((24, 0, 48, 24))]
    t += [pl.crop((i * 24, 0, i * 24 + 24, 24)) for i in range(16)]
    return t


def resize(im, s):
    if s == im.width:
        return im
    # premultiplied alpha so that the border of a sprite does not get a dark halo
    px = im.load()
    pm = Image.new("RGBA", im.size)
    pp = pm.load()
    for y in range(im.height):
        for x in range(im.width):
            r, g, b, a = px[x, y]
            pp[x, y] = (r * a // 255, g * a // 255, b * a // 255, a)
    out = pm.resize((s, s), Image.BOX if s < im.width else Image.NEAREST)
    po = out.load()
    for y in range(s):
        for x in range(s):
            r, g, b, a = po[x, y]
            if a:
                po[x, y] = (min(255, r * 255 // a), min(255, g * 255 // a), min(255, b * 255 // a), a)
    return out


def rgb565(r, g, b):
    return (r >> 3) | ((g >> 2) << 5) | ((b >> 3) << 11)


def main():
    tiles = load_tiles()
    lines = ["// GENERATED by tools/gen_tiles.py - do not edit.",
             "// Sprites: Sokoban (GP2X), Willems Davy (MIT); wall 1001.com (CC-BY-SA 3.0); floor/player Kenney (CC0); box SpriteAttack (CC0).",
             '#include "tiles.h"', ""]
    for s in SIZES:
        data = []
        for im in tiles:
            r = resize(im, s)
            p = r.load()
            for y in range(s):
                for x in range(s):
                    rr, gg, bb, aa = p[x, y]
                    data.append(KEY if aa < 128 else (rgb565(rr, gg, bb) if rgb565(rr, gg, bb) != KEY else KEY ^ 1))
        lines.append("const uint16_t TILES_%d[%d] = {" % (s, len(data)))
        for i in range(0, len(data), 16):
            lines.append("  " + ",".join("0x%04X" % v for v in data[i:i + 16]) + ",")
        lines.append("};")
        lines.append("")
    open(OUT, "w").write("\n".join(lines))
    print("wrote", OUT, len(NAMES), "tiles x", SIZES)


main()
